"""add recipe sections

Revision ID: 0612de3cf1b5
Revises: 15bc317b7ebe
Create Date: 2026-07-24 13:27:40.084790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0612de3cf1b5'
down_revision = '15bc317b7ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'name', name='uq_recipe_section_name')
    )
    with op.batch_alter_table('recipe_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_sections_recipe_id'), ['recipe_id'], unique=False)

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_section_id'), ['section_id'], unique=False)
        batch_op.create_foreign_key(None, 'recipe_sections', ['section_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_section_id'))
        batch_op.drop_column('section_id')

    with op.batch_alter_table('recipe_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_sections_recipe_id'))

    op.drop_table('recipe_sections')
    # ### end Alembic commands ###
