"""refine recipe section relationships and indexes

Revision ID: 1d59308add42
Revises: 0612de3cf1b5
Create Date: 2026-07-24 13:44:59.215935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d59308add42'
down_revision = '0612de3cf1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_position'))
        batch_op.create_index('ix_recipe_ingredients_position', ['recipe_id', 'section_id', 'position'], unique=False)

    with op.batch_alter_table('recipe_sections', schema=None) as batch_op:
        batch_op.create_index('ix_recipe_sections_recipe_position', ['recipe_id', 'position'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_sections', schema=None) as batch_op:
        batch_op.drop_index('ix_recipe_sections_recipe_position')

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index('ix_recipe_ingredients_position')
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_position'), ['recipe_id', 'position'], unique=False)

    # ### end Alembic commands ###
