"""add ordered recipe ingredients and recipe steps

Revision ID: 536a6ce3bf27
Revises: ac318c42d675
Create Date: 2026-07-14 14:13:11.546243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '536a6ce3bf27'
down_revision = 'ac318c42d675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('timer_minutes', sa.Integer(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_recipe_steps_recipe', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_steps', schema=None) as batch_op:
        batch_op.create_index('ix_recipe_steps_recipe_position', ['recipe_id', 'position'], unique=False)

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))
        batch_op.alter_column('recipe_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('ingredient_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_index('ix_recipe_ingredients_position', ['recipe_id', 'position'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index('ix_recipe_ingredients_position')
        batch_op.alter_column('ingredient_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('recipe_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('position')

    with op.batch_alter_table('recipe_steps', schema=None) as batch_op:
        batch_op.drop_index('ix_recipe_steps_recipe_position')

    op.drop_table('recipe_steps')
    # ### end Alembic commands ###
