"""add recipe made history

Revision ID: 5f4dd3590be2
Revises: dd2dc70d73cf
Create Date: 2026-07-28 13:20:37.138074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4dd3590be2'
down_revision = 'dd2dc70d73cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_made_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('made_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_made_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_made_events_made_at'), ['made_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_made_events_recipe_id'), ['recipe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_made_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_made_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_made_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_made_events_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_made_events_made_at'))

    op.drop_table('recipe_made_events')
    # ### end Alembic commands ###
