"""remove legacy recipe instructions column

Revision ID: 829597836095
Revises: 01aa65f17741
Create Date: 2026-07-14 19:25:17.948079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '829597836095'
down_revision = '01aa65f17741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
