"""add recipe updated timestamp

Revision ID: ac318c42d675
Revises: 3fc0136c4651
Create Date: 2026-07-14 13:40:54.694774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac318c42d675'
down_revision = '3fc0136c4651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('updated')

    # ### end Alembic commands ###
