"""add family ratings and family favorite

Revision ID: dd2dc70d73cf
Revises: 51a09f2666f2
Create Date: 2026-07-28 10:35:07.045674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2dc70d73cf'
down_revision = '51a09f2666f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('voter_token', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 10', name='ck_recipe_ratings_rating_1_to_10'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'voter_token', name='uq_recipe_ratings_recipe_voter')
    )
    with op.batch_alter_table('recipe_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_ratings_recipe_id'), ['recipe_id'], unique=False)

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_family_favorite', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('is_family_favorite')

    with op.batch_alter_table('recipe_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_ratings_recipe_id'))

    op.drop_table('recipe_ratings')
    # ### end Alembic commands ###
